local panels = require("examples.42_robot_visualizer.ui.panels")
local playback = require("examples.42_robot_visualizer.playback")

panels.register("perf", "Performance Stats", function(gui, node_id)
    gui.igText("System Status")
    gui.igSeparator()
    local stats = _G._PERF_STATS
    gui.igText(string.format("FPS (ImGui): %.1f", gui.igGetIO_Nil().Framerate))
    gui.igText(string.format("FPS (Raw): %.1f", stats and stats.real_fps or 0))
    gui.igText(string.format("Frame Time: %.3f ms", 1000.0 / gui.igGetIO_Nil().Framerate))
    gui.igSeparator()
    gui.igText("Robot Pose")
    gui.igText(string.format("Pos: (%.2f, %.2f, %.2f)", playback.robot_pose.x, playback.robot_pose.y, playback.robot_pose.z))
    gui.igText(string.format("Yaw: %.2f", playback.robot_pose.yaw))
    gui.igSeparator()
    gui.igText(string.format("Lua Heap: %.2f MB", collectgarbage("count") / 1024))
    gui.igText(string.format("Active Streams: %d", #playback.channels))
end)
