local panels = require("examples.42_robot_visualizer.ui.panels")
local playback = require("examples.42_robot_visualizer.playback")

panels.register("perf", "Performance Stats", function(gui, node_id)
    gui.igText("System Status")
    gui.igSeparator()
    gui.igText("FPS: %.1f", gui.igGetIO_Nil().Framerate)
    gui.igText("Frame Time: %.3f ms", 1000.0 / gui.igGetIO_Nil().Framerate)
    gui.igSeparator()
    gui.igText("Robot Pose")
    gui.igText("Pos: (%.2f, %.2f, %.2f)", playback.robot_pose.x, playback.robot_pose.y, playback.robot_pose.z)
    gui.igText("Yaw: %.2f", playback.robot_pose.yaw)
    gui.igSeparator()
    gui.igText("Lua Heap: %.2f MB", collectgarbage("count") / 1024)
    gui.igText("Active Streams: %d", #playback.channels)
end)
