#version 450
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(set = 0, binding = 2, r32ui) uniform uimage3D all_storage_images[];

layout(push_constant) uniform PushConstants {
    uint out_img;
    uint grid_res;
    float seed;
} pc;

void main() {
    ivec3 pos = ivec3(gl_GlobalInvocationID.xyz);
    if (any(greaterThanEqual(pos, ivec3(pc.grid_res)))) return;

    // Sphere seed
    float d = length(vec3(pos) - vec3(pc.grid_res/2));
    uint val = (d < 32.0) ? 1 : 0;
    
    imageStore(all_storage_images[nonuniformEXT(pc.out_img)], pos, uvec4(val, 0, 0, 0));
}
