#version 450
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 2, r32ui) uniform uimage3D all_storage_images[];
layout(set = 0, binding = 0) buffer GlobalBuffers { uint data[]; } world[];

layout(push_constant) uniform PushConstants {
    uint in_img;
    uint out_img;
    uint dirty_buf;
    uint grid_res;
} pc;

void main() {
    ivec3 pos = ivec3(gl_GlobalInvocationID.xyz);
    if (any(greaterThanEqual(pos, ivec3(pc.grid_res)))) return;

    int neighbors = 0;
    for (int z = -1; z <= 1; z++) {
        for (int y = -1; y <= 1; y++) {
            for (int x = -1; x <= 1; x++) {
                if (x == 0 && y == 0 && z == 0) continue;
                ivec3 n_pos = pos + ivec3(x, y, z);
                if (all(greaterThanEqual(n_pos, ivec3(0))) && all(lessThan(n_pos, ivec3(pc.grid_res)))) {
                    if (imageLoad(all_storage_images[nonuniformEXT(pc.in_img)], n_pos).r > 0) neighbors++;
                }
            }
        }
    }

    uint current = imageLoad(all_storage_images[nonuniformEXT(pc.in_img)], pos).r;
    uint next = 0;
    
    // Survival 4-8. Birth 6-10.
    if (current > 0) {
        if (neighbors >= 4 && neighbors <= 8) next = 1;
    } else {
        if (neighbors >= 6 && neighbors <= 10) next = 1;
    }

    imageStore(all_storage_images[nonuniformEXT(pc.out_img)], pos, uvec4(next, 0, 0, 0));

    if (current != next) {
        ivec3 cp = pos / 16;
        uint chunk_res = pc.grid_res / 16;
        uint chunk_idx = cp.x + (cp.y * chunk_res) + (cp.z * chunk_res * chunk_res);
        atomicOr(world[nonuniformEXT(pc.dirty_buf)].data[chunk_idx], 1);
    }
}
