#version 450
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

struct Sphere {
    vec4 data; // x, y, z, r
};

layout(set = 0, binding = 0, scalar) buffer SphereSoA { Sphere spheres[]; } all_spheres[];
layout(set = 0, binding = 0, scalar) buffer DeltaBuffer { float values[]; } all_deltas[];

layout(push_constant) uniform PC {
    uint sphere_id; // sphere_id is now at offset 0
    uint delta_id;  // delta_id is at offset 4
    uint num_leaves;
} pc;

layout (local_size_x = 256) in;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.num_leaves) return;
    
    // Copy sphere X coordinate to debug buffer.
    // sphere_id passed from Lua should be 4.
    all_deltas[pc.delta_id].values[i] = all_spheres[pc.sphere_id].spheres[i].data.x;
}
